language: node_js

sudo: false

node_js:
  - "0.12"

before_script:
  - node node_modules/grunt-protractor-runner/scripts/webdriver-manager-update
  - npm install -q bower
  - bower install

script:
  - grunt dist test
